version: "3.8"

services:
  proxy:
    container_name: proxy
    image: ghcr.io/laendleenergy/proxy:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
    networks:
      - redis

networks:
  redis:
    name: redis
    external: true  